### ISSUE TITLE
Tile may have also dead and alive status

### ISSUE THREAD

**Issue by sensorario** [sensorario/ppgol#7]
Before open the "empty" pull request we should decide here one thing:

 - create('dead')
 - create('alive')

or 

 - createAlive()
 - createDead()

I think first version is better because we should create programmatically using a condition like

 - create(isAlive())

and isAlive will contain the logic.

Otherwise also second version may be useful in tests: we could write test with "faster" named constructor.

Finally, ... I think both named constructors could be useful.

**Comment by sensorario** [comment]
@camillinif

**Comment by fcamillini** [comment]
I prefer the second one

**Comment by sensorario** [comment]
According to rules, now I’ll open an empty pull request ok?
